routers:
  - name: HQ-ROUTER-01
    enabled: true
    host: 192.168.100.128
    ssh_port: 22
    ssh_user: backup
    private_key: ./ssh-keys/private/id_rsa_pronetivity_rosbackup
    encrypted: true
    enable_binary_backup: true
    enable_plaintext_backup: true
    keep_binary_backup: false
    keep_plaintext_backup: false
    # Optional overrides
    # backup_password: router-specific-password
    # backup_retention_days: 180
    # ssh_args:
    #   look_for_keys: false
    #   allow_agent: false
